### ISSUE TITLE
New lock file format

### ISSUE THREAD

**Issue by SarthakJariwala** [SarthakJariwala/ezconda#19]
The current lock file is a good start but has several limitations. 
It doesn't capture some important information:
- Minimum version of `ezconda` that is  required to work with it
- System architecture
- Platform info
- Machine info

A new lock file format will be `toml` based and with several key fields:

```TOML
[ezconda-min-version]
version = "0.4.0"

[system]
platform = "darwin"
architecture = "64bit"
machine = "x86_64"

[[packages]]
base_url = "https://conda.anaconda.org/conda-forge"
build_number = 1
build_string = "py38h6ced74f_1"
channel = "conda-forge"
dist_name = "numpy-1.19.5-py38h6ced74f_1"
name = "numpy"
platform = "osx-64"
version = "1.19.5"
```

The information in the system table can then be used to verify before installing from the lock file. This is related to #13
